namespace App;

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

/// Order from partner.
[Table(DbConst.table_order)]
[Index(nameof(code), IsUnique = true)]
[Index(nameof(project_id))]

public class OrderModel : AutoGenerateUpdateTime {
	/// PK
	[Key]
	[Column("id")]
	public long id { get; set; }

	/// Unique public code of this order. Generated by our system.
	[Required]
	[Column("code", TypeName = "varchar(255)"), MaxLength(255)]
	public string code { get; set; }

	[Required]
	[ForeignKey(DbConst.table_project)]
	[Column("project_id")]
	public long project_id { get; set; }

	/// Order status (pending, failed, succeed,...)
	[Required]
	[Column("status")]
	public byte status { get; set; }

	/// Total price in ADA which user must pay
	[Required]
	[Column("price_in_ada", TypeName = "decimal(19,6)")]
	public decimal price_in_ada { get; set; }

	/// Transaction id of partner system
	[Required]
	[Column("partner_tx_id")]
	public string partner_tx_id { get; set; }

	/// Order description for display at user side
	[Required]
	[Column("description")]
	public string description { get; set; }

	/// Order items
	[Required]
	[Column("items")]
	public string items { get; set; }

	/// Checksum of order body (items + amount + ...)
	/// Use to validate uniqueness of this order.
	[Required]
	[Column("hmac")]
	public string hmac { get; set; }

	[Column("url_callback")]
	public string? url_callback { get; set; }


	[Required]
	[Column("created_at")]
	public DateTime created_at { get; set; }

	[Column("updated_at")]
	public DateTime? updated_at { get; set; }

	/// When this order is timeouted
	[Required]
	[Column("expired_at")]
	public DateTime expired_at { get; set; }

	[Column("deleted_at")]
	public DateTime? deleted_at { get; set; }

	/// Foreign key property attributes (property name must be same with table name)
	public ProjectModel project { get; set; }
}
