namespace App;

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

[Table(DbConst.table_partner_wallet)]
[Index(nameof(partner_id), nameof(wallet_address))]
public class PartnerWalletModel : AutoGenerateUpdateTime {
	/// PK
	[Key]
	[Column("id")]
	public long id { get; set; }

	/// Point to field `partner.id`.
	[Required]
	[ForeignKey(DbConst.table_partner)]
	[Column("partner_id")]
	public long partner_id { get; set; }

	/// Generated by Cardano. It is unique at Cardano.
	[Required]
	[Column("wallet_address", TypeName = "varchar(255)"), MaxLength(255)]
	public string wallet_address { get; set; }

	/// Wallet type (internal, external, external hardware,...), see `PartnerWalletModelConst.WALLET_TYPE_*`
	[Required]
	[Column("wallet_type")]
	public byte wallet_type { get; set; }

	/// Wallet status (pending, active, inactive,...). See `PartnerWalletModelConst.STATUS_*`
	/// For eg,. when status is active/inactive, then we consider the wallet is valid/invalid for use.
	[Required]
	[Column("wallet_status")]
	public byte wallet_status { get; set; }

	[Required]
	[Column("created_at")]
	public DateTime created_at { get; set; }

	[Column("updated_at")]
	public DateTime? updated_at { get; set; }

	[Column("deleted_at")]
	public DateTime? deleted_at { get; set; }

	/// Foreign key property attributes (property name must be same with table name)
	public PartnerModel partner { get; set; }
}
